document.write('<select name="Province[]" multiple="multiple"  id="Province" >');
//document.write("<option value=></option>");
document.write("<option value=北京市>北京市</option>");
document.write("<option value=上海市>上海市</option>");
document.write("<option value=天津市>天津市</option>");
document.write("<option value=重庆市>重庆市</option>");
document.write("<option value=河北省>河北省</option>");
document.write("<option value=山西省>山西省</option>");
document.write("<option value=辽宁省>辽宁省</option>");
document.write("<option value=吉林省>吉林省</option>");
document.write("<option value=黑龙江>黑龙江</option>");
document.write("<option value=江苏省>江苏省</option>");
document.write("<option value=浙江省>浙江省</option>");
document.write("<option value=安徽省>安徽省</option>");
document.write("<option value=福建省>福建省</option>");
document.write("<option value=江西省>江西省</option>");
document.write("<option value=山东省>山东省</option>");
document.write("<option value=河南省>河南省</option>");
document.write("<option value=湖北省>湖北省</option>");
document.write("<option value=湖南省>湖南省</option>");
document.write("<option value=广东省>广东省</option>");
document.write("<option value=甘肃省>甘肃省</option>");
document.write("<option value=陕西省>陕西省</option>");
document.write("<option value=湖南省>湖南省</option>");
document.write("<option value=内蒙古>内蒙古</option>");
document.write("<option value=广西>广西</option>");
document.write("<option value=四川省>四川省</option>");
document.write("<option value=贵州省>贵州省</option>");
document.write("<option value=云南省>云南省</option>");
document.write("<option value=西藏>西藏</option>");
document.write("<option value=新疆>新疆</option>");
document.write("<option value=香港>香港</option>");
document.write("<option value=奥门>奥门</option>");
document.write("<option value=台湾>台湾</option>");
document.write("</select>");
//$(".chzn-select").chosen();
//$(".chzn-select").chosen().change(function(t){
//console.log(t);
//		var str=$('#Province').val();
//});